name: "Pending Author Response Follow Up"
description: |
  "Add and remove `pending-response` issue labels based comments by the original issue author."
author: siegerts
branding:
  color: blue
  icon: code
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  pending-response-label:
    description: Label to remove indicating that a response is required for further action
    required: true
  actionable-label:
    description: Label added to highlight that a user has responded and a follow-up is required

runs:
  using: "node12"
  main: "dist/index.js"
