name: pending-author-response
on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    if: ${{ !github.event.issue.pull_request }}
    # && contains(github.event.issue.labels.*.name, 'pending-response')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pending-response-label: pending-response
          actionable-label: follow-up
